apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sausage-store-030-13
spec:
  destination:
    name: 'default'
    namespace: std-030-13
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: >-
      https://nexus.praktikum-services.tech/repository/sausage-store-helm-andrey-fedotov-30/
    targetRevision: 0.1.1
    chart: sausage-store
    helm:
      values: |
        global:
          revisionHistoryLimit: 12
          proxyPassHost: backend
          proxyPassPort: 8080
          dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMXpZVzFoYmpwbmJHUjBMWEp2UTA1R1ZGTk9hM2xVY2xWRU4yVTVlSHBHIgoJCX0KCX0KfQ==
          environment: production

        backend:
          replicas: 2
          strategy:
            type: RollingUpdate
          image:
            repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend
            pullPolicy: Always
            tag: latest
          rollingUpdate:
            maxUnavailable: 2
            maxSurge: 20%
          containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          updatePolicy:
            updateMode: "Initial"
          resourcePolicy:
            containerName: "*"
            minAllowed:
              cpu: 0m
              memory: 0Mi
            maxAllowed:
              cpu: 1
              memory: 500Mi
          pg:
            url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYS1reWxycm5oMTN5anFodmx2Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDMwLTEz
            user: c3RkLTAzMC0xMw==
            password: VGVzdHVzcjEyMzQ=
            mongourl: bW9uZ29kYjovL3N0ZC0wMzAtMTM6VGVzdHVzcjEyMzRAcmMxYS0zbmI3cDdqc21idXA2Y3J0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAzMC0xMz90bHM9dHJ1ZQ==

        backend-report:
          strategy:
            type: Recreate
          image:
            repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend-report
            pullPolicy: Always
            tag: latest
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          containerPort: 8080
          minReplicas: 1
          maxReplicas: 5
          resource:
            cpu:
              utilization:
                averageUtilization: 75
          db: bW9uZ29kYjovL3N0ZC0wMzAtMTM6VGVzdHVzcjEyMzRAcmMxYS0zbmI3cDdqc21idXA2Y3J0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAzMC0xMz90bHM9dHJ1ZSZ0bHNBbGxvd0ludmFsaWRDZXJ0aWZpY2F0ZXM9dHJ1ZQ==

        frontend:
          replicas: 1
          strategy:
            type: Recreate
          image:
            repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-frontend
            pullPolicy: Always
            tag: latest
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          containerPort: 80
          ingress:
            tls:
              hosts: fedotov-andrey-30.k8s.praktikum-services.tech
            rules:
              host: fedotov-andrey-30.k8s.praktikum-services.tech
              port: 80
  sources: [ ]
  project: std-030-13
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
syncPolicy:
  automated:
    prune: false
    selfHeal: false

Unable to create application:
  application spec for sausage-store-030-13 is invalid:
    InvalidSpecError:
      Unable to generate manifests in:
        rpc error:
          code = Unknown desc = `helm template . --name-template sausage-store-030-13 --namespace std-030-13 --kube-version 1.26 --values /tmp/8320f70c-af97-457e-90a9-855a360f3548 --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1/Challenge --api-versions acme.cert-manager.io/v1/Order --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AppProject --api-versions argoproj.io/v1alpha1/Application --api-versions argoproj.io/v1alpha1/ApplicationSet --api-versions argoproj.io/v1alpha1/ArgoCDExtension --api-versions autoscaling.k8s.io/v1 --api-versions autoscaling.k8s.io/v1/VerticalPodAutoscaler --api-versions autoscaling.k8s.io/v1/VerticalPodAutoscalerCheckpoint --api-versions autoscaling.k8s.io/v1beta2 --api-versions autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler --api-versions autoscaling.k8s.io/v1beta2/VerticalPodAutoscalerCheckpoint --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2 --api-versions autoscaling/v2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1/Certificate --api-versions cert-manager.io/v1/CertificateRequest --api-versions cert-manager.io/v1/ClusterIssuer --api-versions cert-manager.io/v1/Issuer --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions clustersecret.io/v1 --api-versions clustersecret.io/v1/ClusterSecret --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions dragonflydb.io/v1alpha1 --api-versions dragonflydb.io/v1alpha1/Dragonfly --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions external-secrets.io/v1alpha1 --api-versions external-secrets.io/v1alpha1/ClusterSecretStore --api-versions external-secrets.io/v1alpha1/ExternalSecret --api-versions external-secrets.io/v1alpha1/PushSecret --api-versions external-secrets.io/v1alpha1/SecretStore --api-versions external-secrets.io/v1beta1 --api-versions external-secrets.io/v1beta1/ClusterExternalSecret --api-versions external-secrets.io/v1beta1/ClusterSecretStore --api-versions external-secrets.io/v1beta1/ExternalSecret --api-versions external-secrets.io/v1beta1/SecretStore --api-versions flowcontrol.apiserver.k8s.io/v1beta2 --api-versions flowcontrol.apiserver.k8s.io/v1beta2/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta2/PriorityLevelConfiguration --api-versions flowcontrol.apiserver.k8s.io/v1beta3 --api-versions flowcontrol.apiserver.k8s.io/v1beta3/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta3/PriorityLevelConfiguration --api-versions generators.external-secrets.io/v1alpha1 --api-versions generators.external-secrets.io/v1alpha1/ACRAccessToken --api-versions generators.external-secrets.io/v1alpha1/ECRAuthorizationToken --api-versions generators.external-secrets.io/v1alpha1/Fake --api-versions generators.external-secrets.io/v1alpha1/GCRAccessToken --api-versions generators.external-secrets.io/v1alpha1/Password --api-versions generators.external-secrets.io/v1alpha1/VaultDynamicSecret --api-versions kubevirt.io/v1alpha3 --api-versions kubevirt.io/v1alpha3/KubeVirt --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1/Alertmanager --api-versions monitoring.coreos.com/v1/PodMonitor --api-versions monitoring.coreos.com/v1/Prometheus --api-versions monitoring.coreos.com/v1/PrometheusRule --api-versions monitoring.coreos.com/v1/ServiceMonitor --api-versions monitoring.coreos.com/v1/ThanosRuler --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions snapshot.storage.k8s.io/v1 --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshot --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshotClass --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshotContent --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshot --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotClass --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotContent --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/CSIStorageCapacity --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1beta1/CSIStorageCapacity --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --api-versions velero.io/v1 --api-versions velero.io/v1/Backup --api-versions velero.io/v1/BackupRepository --api-versions velero.io/v1/BackupStorageLocation --api-versions velero.io/v1/DeleteBackupRequest --api-versions velero.io/v1/DownloadRequest --api-versions velero.io/v1/PodVolumeBackup --api-versions velero.io/v1/PodVolumeRestore --api-versions velero.io/v1/ResticRepository --api-versions velero.io/v1/Restore --api-versions velero.io/v1/Schedule --api-versions velero.io/v1/ServerStatusRequest --api-versions velero.io/v1/VolumeSnapshotLocation --include-crds` failed exit status 1:
            Error:
              YAML parse error on sausage-store/charts/backend-report/templates/deployment.yaml:
                error converting YAML to JSON:
                  yaml:
                    line 28: did not find expected key Use --debug flag to render out invalid YAML