apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sausage-store-030-13
spec:
  destination:
    name: 'default'
    namespace: std-030-13
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: >-
      https://nexus.praktikum-services.tech/repository/sausage-store-helm-andrey-fedotov-30/
    targetRevision: 0.1.15
    chart: sausage-store
    helm:
      values: |
        global:
          revisionHistoryLimit: 12
          proxyPassHost: backend
          proxyPassPort: 8080
          dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMXpZVzFoYmpwbmJHUjBMWEp2UTA1R1ZGTk9hM2xVY2xWRU4yVTVlSHBHIgoJCX0KCX0KfQ==
          environment: production

        backend:
          replicas: 1
          strategy:
            type: RollingUpdate
          image:
            repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend
            pullPolicy: Always
            tag: latest
          rollingUpdate:
            maxUnavailable: 2
            maxSurge: 20%
          containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
          updatePolicy:
            updateMode: "Initial"
          resourcePolicy:
            containerName: "*"
            minAllowed:
              cpu: 0m
              memory: 0Mi
            maxAllowed:
              cpu: 1
              memory: 500Mi
          pg:
            url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYS1reWxycm5oMTN5anFodmx2Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDMwLTEz
            user: c3RkLTAzMC0xMw==
            password: VGVzdHVzcjEyMzQ=
            mongourl: bW9uZ29kYjovL3N0ZC0wMzAtMTM6VGVzdHVzcjEyMzRAcmMxYS0zbmI3cDdqc21idXA2Y3J0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAzMC0xMz90bHM9dHJ1ZQ==

        backend-report:
          strategy:
            type: Recreate
          image:
            repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend-report
            pullPolicy: Always
            tag: latest
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          containerPort: 8080
          minReplicas: 1
          maxReplicas: 5
          resource:
            cpu:
              utilization:
                averageUtilization: 75
          db: bW9uZ29kYjovL3N0ZC0wMzAtMTM6VGVzdHVzcjEyMzRAcmMxYS0zbmI3cDdqc21idXA2Y3J0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAzMC0xMz90bHM9dHJ1ZSZ0bHNBbGxvd0ludmFsaWRDZXJ0aWZpY2F0ZXM9dHJ1ZQ==

        frontend:
          replicas: 1
          strategy:
            type: Recreate
          image:
            repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-frontend
            pullPolicy: Always
            tag: latest
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          containerPort: 80
          ingress:
            tls:
              hosts: fedotov-andrey-30.k8s.praktikum-services.tech
            rules:
              host: fedotov-andrey-30.k8s.praktikum-services.tech
              port: 80
  sources: []
  project: std-030-13
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
syncPolicy:
  automated:
    prune: true
    selfHeal: true

