stages:
  - deploy

deploy:
  stage: deploy
  image:
    name: alpine/helm:3.16.2
    entrypoint: [ '' ]
  script:
    - helm package sausage-store-chart
    - echo ${NEXUS_HELM_REPO}
    - ls
    - curl -u ${NEXUS_HELM_USER}:${NEXUS_HELM_PASS} --upload-file sausage-store-*.tgz ${NEXUS_HELM_REPO}