global:
  revisionHistoryLimit: 12
  proxyPassHost: backend
  proxyPassPort: 8080
  environment: production

backend:
  replicas: 1
  strategy:
    type: RollingUpdate
  image:
    repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend
    pullPolicy: Always
    tag: latest
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "20m"
      memory: "128Mi"

  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 20%
  containerPort: 8080
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerName: "*"
    minAllowed:
      cpu: 0m
      memory: 0Mi
    maxAllowed:
      cpu: 1
      memory: 500Mi

backend-report:
  strategy:
    type: Recreate
  image:
    repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-backend-report
    pullPolicy: Always
    tag: latest
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "20m"
      memory: "128Mi"
  containerPort: 8080
  minReplicas: 1
  maxReplicas: 5
  resource:
    cpu:
      utilization:
        averageUtilization: 75

frontend:
  replicas: 1
  strategy:
    type: Recreate
  image:
    repository: gitlab.praktikum-services.ru:5050/std-030-13/sausage/sausage-frontend
    pullPolicy: Always
    tag: latest
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  containerPort: 80
  ingress:
    tls:
      hosts: fedotov-andrey-30.k8s.praktikum-services.tech
    rules:
      host: fedotov-andrey-30.k8s.praktikum-services.tech
      port: 80