# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
data:
  PSQL_DATASOURCE:
  PSQL_USER: c3RkLTAzMC0xMwo=
  PSQL_PASSWORD:
  SPRING_FLYWAY_BASELINE-ON-MIGRATE: true
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogImF6aHpPbTh4ZUZOT2FraDRNakkxUW5vNFZYQk1Za0pUQ2c9PSIKICAgICAgICB9CiAgICB9Cn0gCg==
type: kubernetes.io/dockerconfigjson