---
apiVersion: v1
kind: Secret
metadata:
  name: pg
  labels:
    app: pg
data:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYS1reWxycm5oMTN5anFodmx2Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDMwLTEz
  user: c3RkLTAzMC0xMw==
  password: VGVzdHVzcjEyMzQ=
  mongourl: bW9uZ29kYjovL3N0ZC0wMzAtMTM6VGVzdHVzcjEyMzRAcmMxYS0zbmI3cDdqc21idXA2Y3J0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAzMC0xMz90bHM9dHJ1ZQ==
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMXpZVzFoYmpwbmJHUjBMWEp2UTA1R1ZGTk9hM2xVY2xWRU4yVTVlSHBHIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson