---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
data:
  PSQL_DATASOURCE: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYS1reWxycm5oMTN5anFodmx2Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDMwLTEzP3NzbD10cnVlCg==
  PSQL_USER: c3RkLTAzMC0xMwo=
  PSQL_PASSWORD: VGVzdHVzcjEyMzQK
  SPRING_FLYWAY_BASELINE-ON-MIGRATE: dHJ1ZQo=
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF6TUMweE16cG9Ra3hWZGxoM2VYcDBNbmd0YXpkdGRreDZTd289IgogICAgICAgIH0KICAgIH0KfSAK==
type: kubernetes.io/dockerconfigjson