---
apiVersion: v1
kind: Secret
metadata:
  name: backend-report
  labels:
    app: backend-report
data:
  db: bW9uZ29kYjovL3N0ZC0wMzAtMTM6VGVzdHVzcjEyMzRAcmMxYS0zbmI3cDdqc21idXA2Y3J0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAzMC0xMz90bHM9dHJ1ZSZ0bHNBbGxvd0ludmFsaWRDZXJ0aWZpY2F0ZXM9dHJ1ZQ==
type: Opaque