---
- name: Обновление списка пакетов
  become: true
  apt:
    update_cache: yes

- name: Установить пакет openjdk-16-jdk
  become: true
  apt:
    name: openjdk-16-jdk
    state: present

- name: Установить пакет python3-lxml
  become: true
  apt:
    name: python3-lxml
    state: present

- name: Создадим директорию /opt/sausage-store/bin/
  become: true
  file:
    path: /opt/sausage-store/bin/
    state: directory

- name: Скачать артефакт
  become: true
  get_url:
    url: "https://nexus.praktikum-services.tech/repository/std-030-13-backend/com/yandex/practicum/devops/sausage-store/1.0.1362306/sausage-store-1.0.1362306.jar"
    dest: /opt/sausage-store/bin/sausage-store.jar
    username: "std-030-13"
    password: "{{ password_nexus }}"

- name: Добавим сервисного пользователя
  become: true
  user:
    name: "backend"
    create_home: no
    shell: /sbin/nologin

- name: смена владельца
  become: true
  file:
    path: /opt/sausage-store/bin
    owner: "backend"
    group: "backend"
    recurse: true
    state: directory


- name: Шаблонизация конфига управляет настройками приложения с помощью переменных
  become: true
  template:
    src: /home/student/backend.service
    dest: /etc/systemd/system/sausage-store-backend.service

- name: Перечитываем конфигурацию systemd
  become: true
  systemd:
    daemon_reload: yes

- name: всё готово - запускаем!
  become: true
  service:
    name: sausage-store-backend
    state: restarted