# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF6TUMweE16cG9Ra3hWZGxoM2VYcDBNbmd0YXpkdGRreDZTd289IgogICAgICAgIH0KICAgIH0KfSAK
type: kubernetes.io/dockerconfigjson