# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMXpZVzFoYmpwbmJHUjBMWEp2UTA1R1ZGTk9hM2xVY2xWRU4yVTVlSHBHIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson