# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogImRlcGxveTpld05NcngzVWtHdXhlWXk1bnFvaiIKICAgICAgICB9CiAgICB9Cn0K
type: kubernetes.io/dockerconfigjson