---
apiVersion: v1
kind: Secret
metadata:
  name: pg
  labels:
    app: pg
data:
  url: {{.Values.pg.url}}
  user: {{.Values.pg.user}}
  password: {{.Values.pg.password}}
  mongourl: {{.Values.pg.mongourl}}

type: Opaque