---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{.Release.Namespace}}
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    route:
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30m
      receiver: "telegram"
      routes:
      - receiver: "telegram"
        group_wait: 10s
        match_re:
          severity: critical|warning
        continue: true

    receivers:
    - name: "telegram"
      telegram_configs:
      - send_resolved: true
        bot_token: '{{ .Values.telegramBotToken }}'
        chat_id: -1002138916913
        message: "std-030-13{{ .Annotations.description }}{{ range .Alerts }}\n{{ end }}"

---
telegram_hook_url: 'https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage'
telegramBotToken: "5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs"
