cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - deploy

deploy:
  stage: deploy
  image:
    ?
  before_script:
    -
    -
    -
  script:
    -
    -
    -

