stages:
  - deploy
  - test
deploy-backend-job:
  stage: deploy
  image: bitnami/kubectl:1.31.1
  script:
    - mkdir .kube
    - echo "$kubeconfig" | base64 -d > .kube/config
    - export KUBECONFIG=.kube/config
    - kubectl apply -f kubernetes/backend
    - rm -f .kube/config
  rules:
    - when: manual

