# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: mongodb
#  labels:
#    app: mongodb
#data:
#  db: bW9uZ29kYjovL3N0ZC0wMTctMDA2OlRlc3R1c3IxMjM0QHJjMWMtYmlmeDdiYmUzZGQ5Y2k2MC5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3N0ZC0wMTctMDA2P3Rscz10cnVlJnRsc0FsbG93SW52YWxpZENlcnRpZmljYXRlcz10cnVl
#type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMXpZVzFoYmpwbmJHUjBMWEp2UTA1R1ZGTk9hM2xVY2xWRU4yVTVlSHBHIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-report
  labels:
    app: backend-report
data:
  DB: bW9uZ29kYjovLzpAOjI3MDE4Lz90bHM9dHJ1ZSZ0bHNBbGxvd0ludmFsaWRDZXJ0aWZpY2F0ZXM9dHJ1ZQo=
type: Opaque